window.CAR_INVENTORY = [
  {
    id: "toyota-hiace",
    images: ["Vehicle log/c 5.jpeg"],
    make: "Toyota",
    model: "Hiace",
    year: "Not confirmed",
    price: 0,
    priceText: "Price on request",
    condition: "Imported commercial vehicle",
    mileage: "Not confirmed",
    transmission: "Not confirmed",
    engine: "Not confirmed",
    fuel: "Not confirmed",
    location: "Lagos, Nigeria",
    description: "Toyota Hiace commercial vehicle noted in original container arrival documentation.",
    whatsapp: "2348033969149",
    phone: "+2348033969149",
    availability: "AVAILABLE"
  },
  {
    id: "jaguar-xe-p250",
    images: ["Vehicle log/c 3.jpeg"],
    make: "Jaguar",
    model: "XE P250",
    year: "Not confirmed",
    price: 0,
    priceText: "Price on request",
    condition: "Imported luxury sedan",
    mileage: "Not confirmed",
    transmission: "Not confirmed",
    engine: "Not confirmed",
    fuel: "Not confirmed",
    location: "Lagos, Nigeria",
    description: "Jaguar XE P250 documented during container arrival handling and available on enquiry.",
    whatsapp: "2348033969149",
    phone: "+2348033969149",
    availability: "AVAILABLE"
  },
  {
    id: "range-rover-sport",
    images: ["Vehicle log/c 17.jpeg"],
    make: "Land Rover",
    model: "Range Rover Sport",
    year: "Not confirmed",
    price: 0,
    priceText: "Price on request",
    condition: "Imported premium SUV",
    mileage: "Not confirmed",
    transmission: "Not confirmed",
    engine: "Not confirmed",
    fuel: "Not confirmed",
    location: "Lagos, Nigeria",
    description: "Range Rover Sport recorded from original port-arrival documentation and available on enquiry.",
    whatsapp: "2348033969149",
    phone: "+2348033969149",
    availability: "AVAILABLE"
  },
  {
    id: "mercedes-s-class",
    images: ["Vehicle log/c 16.jpeg"],
    make: "Mercedes-Benz",
    model: "S-Class",
    year: "Not confirmed",
    price: 0,
    priceText: "Price on request",
    condition: "Imported luxury vehicle",
    mileage: "Not confirmed",
    transmission: "Not confirmed",
    engine: "Not confirmed",
    fuel: "Not confirmed",
    location: "Lagos, Nigeria",
    description: "Mercedes-Benz S-Class documentation available for current confirmation and pricing.",
    whatsapp: "2348033969149",
    phone: "+2348033969149",
    availability: "AVAILABLE"
  }
];
